<a href="https://colab.research.google.com/github/skimmy/learn-dl/blob/main/sgd/notebooks/LDL_SGD01_BasicGradient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# MIT License

# Copyright (c) 2024 Michele Schimd

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

In [2]:
import torch

In [11]:
x = torch.arange(5.0)
print(x)
x.requires_grad_(True)
print(x)
y = torch.dot(x,x)
print(y)
y.backward()
print(x.grad)

tensor([0., 1., 2., 3., 4.])
tensor([0., 1., 2., 3., 4.], requires_grad=True)
tensor(30., grad_fn=<DotBackward0>)
tensor([0., 2., 4., 6., 8.])


In [12]:
x.grad.zero_()
y = x.sum()
y.backward()
print(x.grad)

tensor([1., 1., 1., 1., 1.])


## References
*  D2L: [2.5 - Automatic Differentiation](https://d2l.ai/chapter_preliminaries/autograd.html)

Notes
* D2L: Dive Into Deep Learning